"""
Shared constants for Codur.
"""

DEBUG_TRUNCATE_SHORT = 500
DEBUG_TRUNCATE_LONG = 1000
GREETING_MAX_WORDS = 3
DEFAULT_MAX_BYTES = 200_000
DEFAULT_MAX_RESULTS = 200
DEFAULT_CLI_TIMEOUT = 600
DEFAULT_MAX_ITERATIONS = 10
